#############################################
# 🧱 Etapa 1 - Build da aplicação Angular
#############################################
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . .

RUN npm run merge-i18n -- -s src/themes/uricer/assets/i18n && \
    npm run build:prod


#############################################
# 🚀 Etapa 2 - Runtime (produção)
#############################################
FROM node:22-alpine

RUN npm install --global pm2

WORKDIR /app

COPY --chown=node:node --from=build /app/dist ./dist
COPY --chown=node:node --from=build /app/config ./config
COPY --chown=node:node --from=build /app/docker/dspace-ui.json ./dspace-ui.json

ENV NODE_ENV=production
USER node

EXPOSE 4000

CMD ["pm2-runtime", "start", "dspace-ui.json", "--json"]
