FROM node:22 AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run merge-i18n -- -s src/themes/uricer/assets/i18n
RUN npm run build:prod

# Runtime stage
FROM node:22-alpine
RUN npm install -g pm2

WORKDIR /app

COPY --chown=node:node --from=build /app/dist ./dist
COPY --chown=node:node config ./config
COPY --chown=node:node docker/dspace-ui.json ./dspace-ui.json

ENV NODE_ENV=production
USER node
EXPOSE 4000
CMD pm2-runtime start dspace-ui.json --json
